export const FLOATING_CUSTOMER_TAB_BAR_HEIGHT = 72;
export const FLOATING_CUSTOMER_TAB_BAR_MARGIN = 14;
export const FLOATING_CUSTOMER_TAB_BAR_CLEARANCE =
  FLOATING_CUSTOMER_TAB_BAR_HEIGHT + FLOATING_CUSTOMER_TAB_BAR_MARGIN + 24;
